CREATE TABLE EMPLOYEE (
    ENAME VARCHAR(20) NOT NULL,
    ESRNO VARCHAR(7) PRIMARY KEY,
    BDATE DATE,
    ADDRESS VARCHAR(20),
    SEX CHAR(1),
    SALARY DECIMAL(7,2),
    MGRSRNO VARCHAR(6),
    DNO INT(3)
);


INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('AJIT NAYAK', '133100', STR_TO_DATE('1955-04-25', '%Y-%m-%d'), '73 BOSTON', 'M', 35000, '', 1);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('SATYA', '495823', STR_TO_DATE('1966-07-17', '%Y-%m-%d'), '26 FINE OAK', 'M', 32770, '133100', 4);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('AJIT BEHERA', '315152', STR_TO_DATE('1971-07-09', '%Y-%m-%d'), '10 KALINGA', 'M', 32802, '133100', 3);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('UMASHANKAR', '216852', STR_TO_DATE('1967-07-17', '%Y-%m-%d'), '26 FINE OAK', 'M', 32770, '133100', 2);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('BHAGWAT', '215152', STR_TO_DATE('1971-03-23', '%Y-%m-%d'), '55 FLORIDA', 'M', 32802, '216852', 2);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('MEENAKSHI', '334548', STR_TO_DATE('1979-04-25', '%Y-%m-%d'), '73 BRIKLY', 'F', 25125, '315152', 3);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('JASWASI', '215485', STR_TO_DATE('1979-08-12', '%Y-%m-%d'), '17 BOSTON', 'M', 20500, '495823', 4);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('NIHAR NAYAK', '334524', STR_TO_DATE('1966-12-17', '%Y-%m-%d'), '73 DALLAS', 'M', 29105, '315152', 3);
INSERT INTO EMPLOYEE (ENAME, ESRNO, BDATE, ADDRESS, SEX, SALARY, MGRSRNO, DNO) VALUES ('DEBASMITA', '295485', STR_TO_DATE('1970-04-16', '%Y-%m-%d'), '1 QUEENS LAND', 'F', 20500, '216852', 2);

CREATE TABLE DEPARTMENT (
    DNAME VARCHAR(12),
    DNUMBER INT(2) PRIMARY KEY,
    MGRSRNO VARCHAR(6),
    MGRSTARTD DATE
);


INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSRNO, MGRSTARTD) VALUES ('RESEARCH', 4, '495823', STR_TO_DATE('1999-04-20', '%Y-%m-%d'));
INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSRNO, MGRSTARTD) VALUES ('ADMIN', 1, '133100', STR_TO_DATE('1988-01-06', '%Y-%m-%d'));
INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSRNO, MGRSTARTD) VALUES ('PROJECT', 2, '216852', STR_TO_DATE('1999-07-17', '%Y-%m-%d'));
INSERT INTO DEPARTMENT (DNAME, DNUMBER, MGRSRNO, MGRSTARTD) VALUES ('ACADEMIC', 3, '315152', STR_TO_DATE('1989-12-20', '%Y-%m-%d'));

CREATE TABLE DEPT_LOCATIONS (
    DNUMBER INT(2),
    DLOCATION VARCHAR(12)
);
SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM DEPT_LOCATIONS;

INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (2, 'SINGAPORE');
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (1, 'INDIA');
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (4, 'QUEENSLAND');
INSERT INTO DEPT_LOCATIONS (DNUMBER, DLOCATION) VALUES (3, 'LONDON');

CREATE TABLE PROJECT (
    PNAME VARCHAR(18),
    PNUMBER INT(3) PRIMARY KEY,
    PLOCATION VARCHAR(15),
    DNUM INT(2)
);

INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM) VALUES ('NETWORKING', 11, 'KOREA', 4);
INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM) VALUES ('BIO INFORMATICS', 19, 'SOUTH AFRICA', 3);
INSERT INTO PROJECT (PNAME, PNUMBER, PLOCATION, DNUM) VALUES ('LINUX', 17, 'INDIA', 2 ); 

CREATE TABLE WORKS_ON (
    ESRNO VARCHAR(6),
    PNO INT(3),
    HOURS DECIMAL(5,2)
);


INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('315152', 19, 1.25) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('334548', 19, 3.28) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('215485', 17, 1.25) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('295485', 17, 5.35) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('334548', 19, 2.54) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('295485', 17, 7.2) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('216852', 17, 2.41); 
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('334524', 19, 3.24) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('295485', 17, 1.36) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('495823', 11, 2.36) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('215152', 17, 1.25) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('495823', 11, 3.14) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('315152', 19, 2.05) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('334548', 19, 2.5) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('495823', 11, 5.27); 
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('215152', 17, 2.32) ;
INSERT INTO WORKS_ON (ESRNO, PNO, HOURS) VALUES ('495823', 11, 4.15) ;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_MGRSRNO
FOREIGN KEY(MGRSRNO)
REFERENCES EMPLOYEE(ESRNO) 
ON DELETE CASCADE;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_DNO
FOREIGN KEY(DNO)
REFERENCES DEPARTMENT(DNUMBER)
ON DELETE CASCADE; 

ALTER TABLE DEPARTMENT
ADD CONSTRAINT FK_MGRSRNO_DEPT
FOREIGN KEY(MGRSRNO)
REFERENCES EMPLOYEE(ESRNO)
ON DELETE CASCADE;

ALTER TABLE DEPT_LOCATIONS
ADD CONSTRAINT FK_DNUMBER_DEPT_LOCATIONS
FOREIGN KEY(DNUMBER)
REFERENCES DEPARTMENT(DNUMBER)
ON DELETE CASCADE;

ALTER TABLE PROJECT
ADD CONSTRAINT FK_DNUM_PROJECT
FOREIGN KEY(DNUM)
REFERENCES DEPARTMENT(DNUMBER)
ON DELETE CASCADE; 

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_ESRNO_WORKS_ON
FOREIGN KEY(ESRNO)
REFERENCES EMPLOYEE(ESRNO)
ON DELETE CASCADE;

ALTER TABLE WORKS_ON
ADD CONSTRAINT FK_PNO_WORKS_ON
FOREIGN KEY(PNO)
REFERENCES PROJECT(PNUMBER)
ON DELETE CASCADE;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;
SELECT * FROM DEPT_LOCATIONS;
SELECT * FROM PROJECT;
SELECT * FROM WORKS_ON;

-- Major Question 1
-- A) List the salary of all the employees.
SELECT ENAME, SALARY
FROM EMPLOYEE;

-- B) Display the names of all employees with any “A” at any place of the name.
SELECT ENAME
FROM EMPLOYEE
WHERE ENAME LIKE '%A%';

-- C) Show all employees who were hired in the first half of the month (Before the 16th of the month).
SELECT *
FROM EMPLOYEE
WHERE DAY(BDATE) <= 15;

-- D) Display the name of all female employees.
SELECT ENAME
FROM EMPLOYEE
WHERE SEX = 'F';

-- E) Display the employee who is paid most in the company.
SELECT ENAME, SALARY
FROM EMPLOYEE
ORDER BY SALARY DESC
LIMIT 1;

-- Major Question 2
-- A) Display employee name, address, department no and department name.
SELECT e.ENAME, e.ADDRESS, e.DNO, d.DNAME
FROM EMPLOYEE e
INNER JOIN DEPARTMENT d ON e.DNO = d.DNUMBER;

-- B) Display all the employees who are not in ACADEMIC department.
SELECT *
FROM EMPLOYEE
WHERE DNO NOT IN (SELECT DNUMBER FROM DEPARTMENT WHERE DNAME = 'ACADEMIC');

-- C) Display SATYA’S project location.
SELECT P.PLOCATION
FROM EMPLOYEE E
JOIN WORKS_ON W ON E.ESRNO = W.ESRNO
JOIN PROJECT P ON W.PNO = P.PNUMBER
WHERE E.ENAME = 'SATYA';

-- D) Find the total working hours of each female employee.
SELECT e.ENAME, SUM(w.HOURS) AS Total_Working_Hours
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
WHERE e.SEX = 'F'
GROUP BY e.ENAME;

-- E) Display the details of the people whose projects are located at SOUTH AFRICA.
SELECT e.ENAME, e.ADDRESS, p.PNAME, p.PLOCATION
FROM EMPLOYEE e
JOIN WORKS_ON w ON e.ESRNO = w.ESRNO
JOIN PROJECT p ON w.PNO = p.PNUMBER
WHERE p.PLOCATION = 'SOUTH AFRICA';













